options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ci-demo:$SHORT_SHA', '.']

  # 2) Send to Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ci-demo:$SHORT_SHA']

  # 3) Deploy into Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy ci-demo \
          --image=gcr.io/$PROJECT_ID/ci-demo:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --quiet

images:
  - 'gcr.io/$PROJECT_ID/ci-demo:$SHORT_SHA'
